---
- name: ensure docker package is installed and up to date
  yum:
    name: "{{ item  }}"
    state: latest
  with_items:
    - docker

- name: ensure docker service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker
