---
- name: ensure developer dependency packages are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - apt-transport-https
    - python-software-properties
