---
- name: ensure java-related development packages are present
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - openjdk-6-jdk
    - openjdk-7-jdk
