---
- name: ensure docker requirements packages are installed
  action: "{{ docker_package_info.pkg_mgr }}"
  args: docker_package_info.args
  with_items: docker_package_info.pre_pkgs
  when: docker_package_info.pre_pkgs|length > 0

- name: ensure docker repository public key is installed
  command: apt-key adv --recv-key --keyserver hkp://keyserver.ubuntu.com:80 36A1D7869245C8950F966E92D8576A8BA88D21E9
  register: docker_key
  changed_when: docker_key.stderr.find("imported") != -1
  when: ansible_distribution == "Ubuntu"

- name: ensure docker repository is enabled
  apt_repository:
    repo: deb https://get.docker.io/ubuntu docker main
    update_cache: yes
    state: present
  when: ansible_distribution == "Ubuntu"

- name: ensure docker packages are installed
  action: "{{ docker_package_info.pkg_mgr }}"
  args: docker_package_info.args
  with_items: docker_package_info.pkgs
  when: docker_package_info.pkgs|length > 0

- name: ensure docker service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker
