---
- name: ensure docker dependency packages are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - apt-transport-https
    - python-software-properties

- name: ensure docker repository public key is installed
  command: apt-key adv --recv-key --keyserver hkp://keyserver.ubuntu.com:80 36A1D7869245C8950F966E92D8576A8BA88D21E9
  register: docker_key
  changed_when: docker_key.stderr.find("imported") != -1

- name: ensure docker repository is enabled
  apt_repository:
    repo: deb https://get.docker.io/ubuntu docker main
    update_cache: yes
    state: present

- name: ensure lxc-docker is installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - lxc-docker

- name: ensure docker service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker

