---
- name: ensure python virtualenv packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - python-pip
    - python-virtualenv
    - virtualenv-clone
    - virtualenvwrapper
