---
- name: ensure compilers and build tools are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - build-essential
    - cabal-install
    - gfortran
    - ghc

- name: ensure debugging-related system packages are present
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - gdb
    - valgrind

- name: ensure vcs command-line tools are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - bzr
    - cvs
    - darcs
    - git-all
    - git-annex
    - git-email
    - git-extras
    - git-flow
    - git-remote-gcrypt
    - git-stuff
    - mercurial
    - subversion
